---
- name: Gitlab CI omnibus Installation
  hosts: gitlab_ci_server
  become: true
  tasks:

  - name: Create directoies
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

  - name: Run Gitlab CI container
    docker_container:
      name: gitlab_ci
      image: 'gitlab/gitlab-ce:latest'
      state: started
      restart: yes
      volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      ports:
      - '80:80'
      - '443:443'
      - '2222:22'
      env:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'gitlab-ci-url'
