version: "3.3"

services:
  post_db:
    container_name: post_db
    image: ${DB_IMAGE}
    volumes:
    - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db

  comment:
    container_name: comment
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases: 
        - comment
      back_net:
    depends_on:
    - post

  post:
    container_name: post
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      front_net:
        aliases: 
        -  post
      back_net:
    depends_on:
    - post_db

  ui:
    container_name: ui
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
    - ${UI_PORTS}
    networks:
    - front_net
    depends_on:
    - comment

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
      - subnet: "10.0.1.0/24"

  back_net:
    ipam:
      config:
      - subnet: "10.0.2.0/24"
