# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :'docker-instance' => {
    :hosts => {
      :'appserver' => {
        :box_name => "ubuntu/xenial64",
        :ip_addr => '192.168.10.200',
        :host_mem => '512',
      },
    },
    :vars => {
    },
    :ansible_extra_vars => {
      "deploy_user" => "ubuntu",
    },
  },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |group_name, host_name|
    host_name[:hosts].each do |host_config, host_vars|
      config.vm.define host_config do |box|

        box.vm.box = "google/gce"

        box.vm.provider :google do |google, override|

          override.ssh.username = "appuser"
          override.ssh.private_key_path = "~/.ssh/appuser"
          google.zone = "europe-west1-b"

          google.zone_config "europe-west1-b" do |zone|
            zone.name = "testing-vagrant"
            zone.image_family = 'ubuntu-1604-lts'
            zone.tags = ['default-allow-ssh']
          end
        end
        
        config.vm.provision 'ansible' do |ansible|
          ansible.playbook = 'playbooks/packer_docker.yml'
          ansible.groups = {
            group_name => host_name[:hosts].keys,
            group_name.to_s + ":vars" => host_name[:vars],
          }
          ansible.extra_vars = host_name[:ansible_extra_vars]
        end
      end
    end
  end
end
